$schema: https://json-schema.org/draft/2020-12/schema
type: object
description: 配置文件模式检查
required:
  - samples_tsv
properties:
  samples_tsv:
    type: string
    description: 样本表文件路径, 包含样本名称和 FASTQ 文件路径, 后续添加更多元数据信息
    minLength: 1
  conda:
    description: Conda 环境配置
    type: object
    properties:
      python:
        type: string
      fastqc:
        type: string
      multiqc:
        type: string
      fastp:
        type: string
      bwa:
        type: string
      samtools:
        type: string
      fgbio:
        type: string
      picard:
        type: string
      bcftools:
        type: string
      bedtools:
        type: string
    additionalProperties: true
  threads:
    type: object
    description: 线程配置
    properties:
      low:
        type: integer
        minimum: 1
        description: 低线程任务
      medium:
        type: integer
        minimum: 1
        description: 中等线程任务
      high:
        type: integer
        minimum: 1
        description: 高线程任务
  database:
    type: object
    description: 数据库配置
    properties:
      hg19:
        type: string
        description: 参考基因组路径
      region:
        type: string
        description: 探针靶向区域文件路径
      region_slop500bp:
        type: string
        description: 探针靶向区域 500bp 扩展文件路径
      anno_500snp:
        type: string
        description: 500 SNP 注释文件路径
  resources:
    type: object
    description: 运行资源配置
    properties:
      java_mem:
        type: string
        description: Java 堆内存限制, 例如 "-Xmx8G"
      tmp_dir:
        type: string
        description: 临时目录路径, 用于存储中间文件
