# conda 环境配置
conda:
  python: python3.12
  fastqc: basic
  multiqc: basic
  fastp: basic2
  bwa: ddcfdna
  samtools: ddcfdna
  fgbio: ddcfdna
  picard: ddcfdna
  bedtools: ddcfdna
  bcftools: ddcfdna

# 线程数配置
threads:
  low: 4
  medium: 8
  high: 16

# 数据库配置
database:
  # 参考基因组, 需要提前建 bwa/samtools/picard 索引
  hg19: /data/mengxf/Database/reference/hg19/hg19.fa
  region: /data/mengxf/GitHub/KML-dd-cfDNA/wf-igt-500snp/assets/probeCov.predict.bed
  region_slop500bp: /data/mengxf/GitHub/KML-dd-cfDNA/wf-igt-500snp/assets/probeCov.predictSlop500bp.bed
  anno_500snp: /data/mengxf/GitHub/KML-dd-cfDNA/wf-igt-500snp/assets/loci.anno.vcf

# 运行资源
resources:
  # Java 堆内存限制. fgbio/picard 等软件需要设置
  java_mem: "-Xmx8G"
